Develop
waseembrare/portfolio pull request #5
Opened 2021-01-20 12:58 UTC by waseembrare

Please review my html and css files. 

No media queries have been completed so not a responsive page yet. 

Will be working on in-progress branch on media queries until I hear back. 

Look forward to the critique! 

Thanks

2021-01-20 16:54 UTC, norayna requested changes
General comment - great PR description, try and do something similar with the PR title itself - describe briefly what has been done in the PR in the title

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +	margin-right: 1.5rem;
or padding on top and bottom

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +	margin-bottom: 7vh;
I'm not sure that the view height is what you want to base your margins off of here, unless you're really sure. It doesn't make too much sense to base the height of elements off of the height of the viewport because it's sort of arbitrary and the page scrolls anyway

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +.cta-button, .cta-left {
`cta-left` not semantic - what if we decide to put it on the right tomorrow

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +	margin-bottom: 7vh;
again vh for padding/margin

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +.cta {
although cta is known to mean call to action, it's best to type it out for those who might not know

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +.cta-button, .cta-left {
wait it seems like `cta-left` isn't used - delete

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +.cta-q {
call-to-action-question

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +}
again left right not really semantic

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +}
why not just give them all the same class?

2021-01-20 16:54 UTC, norayna commented on css/styles.css
> +.fab {
why is this class called fab? if it's a reused class from elsewhere then you should instead create a new class and add it to those elements (and use a semantic name like "social-icons" or something)

2021-01-20 16:54 UTC, norayna commented on css/all.css
> +/*!
Why do you have this file downloaded? I think you're already using a spreadsheet for these icons and linking to an online version of it in your HTML?

2021-01-20 16:54 UTC, norayna commented on index.html
> +				<h1>waseembrare</h1>
maybe you want to have it with the space in the middle? so it matches with a google search?

2021-01-20 16:54 UTC, norayna commented on index.html
> +				<h2>//developer</h2>
do you want this to have the // given that it's not displayed?

2021-01-20 16:54 UTC, norayna commented on index.html
> +					<i class="fab fa-behance grow"></i>
grow class named after what it looks like - breaks separation of concerns. since all the social icons grow I would just give them a common class that has the growth properties in it

2021-01-20 16:54 UTC, norayna commented on index.html
> +					<p>HTML // CSS<br><br>Figma // Illustrator</p>
don't use br tag - bad practice - use separate p tags instead

2021-01-20 16:54 UTC, norayna commented on index.html
> +					<p>HTML // CSS<br><br>Figma // Illustrator</p>
here and everywhere

2021-01-21 08:34 UTC, waseembrare commented on README.md
> +<p>A portfolio website to display the projects I have completed whilst on the full stack dev course at iO-academy, as well as in my spare time for fun!</p>
thanks for heads up - changed

2021-01-21 08:41 UTC, waseembrare commented on css/styles.css
> +}*/
I've removed the commented out code throughout and have saved an experimental file locally to play around with effects. 

The image needed to be encoded in base 64 and this was the url. I've never seen a link like it but it worked 🤷 😄

2021-01-21 08:45 UTC, waseembrare commented on css/all.css
> +/*!
yes true, this was installed before Charlie suggested using font-awesome's cdn. Didn't clean up. Deleted.

2021-01-21 08:46 UTC, waseembrare commented on index.html
> +				<h2>//developer</h2>
removed //

2021-01-21 08:47 UTC, waseembrare commented on index.html
> +				<h1>waseembrare</h1>
spaced between fname and lname

2021-01-21 08:50 UTC, waseembrare commented on index.html
> +					<p>HTML // CSS<br><br>Figma // Illustrator</p>
removed all br tags

2021-01-21 08:58 UTC, waseembrare commented on index.html
> +					<i class="fab fa-behance grow"></i>
changed to icon-animation class

2021-01-21 10:46 UTC, waseembrare commented on css/styles.css
> +
text-focus-in animation. Is there a standard way to indicate this. I just pasted in their css class code and it appeared directly above selector

2021-01-21 15:40 UTC, waseembrare commented on css/styles.css
> +	font-size: 62.5%
changed to 10px

2021-01-21 15:41 UTC, waseembrare commented on css/styles.css
> +}
changed

2021-01-21 15:41 UTC, waseembrare commented on css/styles.css
> +}
sorted

2021-01-21 15:42 UTC, waseembrare commented on css/styles.css
> +.cta-button, .cta-left {
changed to be more semantic

2021-01-21 15:42 UTC, waseembrare commented on css/styles.css
> +.cta {
changed

2021-01-21 15:43 UTC, waseembrare commented on css/styles.css
> +}
changed to about-0image and about-description

2021-01-21 15:47 UTC, waseembrare commented
Changed the css and html to reflect the 1st PR you completed for me.

Media queries are not fantastic but at this stage I would would rather try and get something into main 🤞

Thanks

2021-01-21 16:26 UTC, norayna approved these changes

2021-01-21 16:30 UTC, merged